### GET / -> Hello, World!
GET http://rpi4:3000/ HTTP/1.1

### POST login successfully
### curl -X POST localhost:1323/login -d "username=jon&password=nope"
POST http://rpi4:3000/login
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

username=nui&password=Welcome1

### POST login as non admin
### curl -X POST localhost:1323/login -d "username=jon&password=nope"
POST http://rpi4:3000/login
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

username=sam&password=Welcome1

### POST login successfully
### curl -X POST localhost:1323/login -d "username=jon&password=nope"
POST http://rpi4:3000/login
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

username=nuch&password=Welcome1
### GET private using nui's token
GET http://rpi4:3000/private HTTP/1.1
Content-Type: application/json; charset=UTF-8
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6dHJ1ZSwiZXhwIjoxNjIwMzAxMDY3LCJpZCI6MSwibmFtZSI6Im51aSJ9.v_XdEdzabges2WMgywZBI1Iw5vlocKVyZNu-W3ckJ_TMGU_g3_-xAWawOaKmh6fowHdsb7QuPUX8epzUhEYkLQ

### GET private using sam's token
GET http://rpi4:3000/private HTTP/1.1
Content-Type: application/json; charset=UTF-8
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6ZmFsc2UsImV4cCI6MTYyMDIyODYzOSwiaWQiOjIsIm5hbWUiOiJzYW0ifQ.mU_TzYi8LqCJWtP4oCT3o9iTbix3TMjMJAArnqummjRLvXhOp5CmSDjt8uRkvymHL27eFqCRSvAO4SWiWPvi_A
### GET admin while admin is true in token
GET http://rpi4:3000/admin HTTP/1.1
Content-Type: application/json; charset=UTF-8
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6dHJ1ZSwiZXhwIjoxNjIwMzAxMDY3LCJpZCI6MSwibmFtZSI6Im51aSJ9.v_XdEdzabges2WMgywZBI1Iw5vlocKVyZNu-W3ckJ_TMGU_g3_-xAWawOaKmh6fowHdsb7QuPUX8epzUhEYkLQ

### GET admin while admin is false in token
GET http://rpi4:3000/admin HTTP/1.1
Content-Type: application/json; charset=UTF-8
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6ZmFsc2UsImV4cCI6MTYyMDIyODYzOSwiaWQiOjIsIm5hbWUiOiJzYW0ifQ.mU_TzYi8LqCJWtP4oCT3o9iTbix3TMjMJAArnqummjRLvXhOp5CmSDjt8uRkvymHL27eFqCRSvAO4SWiWPvi_A

### Renew access token
POST http://rpi4:3000/token HTTP/1.1
Content-Type: application/json; charset=UTF-8

{ "refresh_token": "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjAzMTM1NDEsInN1YiI6MX0.BQcYHuteyTXQuxcCF92obB6xxMa4stCIMihHfCzirDpmYdE-Pc3hOix7MDp0vWQsmaI3_J0t4CsI4EwXU2OZ-Q"}

###
nui
  "access_token": "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6dHJ1ZSwiZXhwIjoxNjIwMzAxMDY3LCJpZCI6MSwibmFtZSI6Im51aSJ9.v_XdEdzabges2WMgywZBI1Iw5vlocKVyZNu-W3ckJ_TMGU_g3_-xAWawOaKmh6fowHdsb7QuPUX8epzUhEYkLQ",
  "refresh_token": "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjAzODY1NjcsInN1YiI6MX0.xzDcsZx-DhYdLdq2YlkSdRtXID7tKQuUFKCF_9XYJih18J3DN1aS47ax-7KjjxfTJrv2c36Dv3z6utSVp2IYOg"sam  
  "access_token": "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6ZmFsc2UsImV4cCI6MTYyMDIyODYzOSwiaWQiOjIsIm5hbWUiOiJzYW0ifQ.mU_TzYi8LqCJWtP4oCT3o9iTbix3TMjMJAArnqummjRLvXhOp5CmSDjt8uRkvymHL27eFqCRSvAO4SWiWPvi_A",
  "refresh_token": "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjAzMTQxMzksInN1YiI6Mn0.rKx6r4Z_e5P3Ma7QdDpipnzbSiNag7FDMQ1TE_qYjLliYeXvoDZZLhXr13v23FawnoYPWh3EK9QFcgYuu8kcsA"