### GET / -> Hello, World!
GET http://rpi4:3000/ HTTP/1.1

### POST login successfully
### curl -X POST localhost:1323/login -d "username=jon&password=nope"
POST http://rpi4:3000/login
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

username=nui&password=Welcome1

### POST login as non admin
### curl -X POST localhost:1323/login -d "username=jon&password=nope"
POST http://rpi4:3000/login
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

username=sam&password=Welcome1

### POST login successfully
### curl -X POST localhost:1323/login -d "username=jon&password=nope"
POST http://rpi4:3000/login
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

username=nuch&password=Welcome1
### GET private using nui's token
GET http://rpi4:3000/private HTTP/1.1
Content-Type: application/json; charset=UTF-8
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6dHJ1ZSwiZXhwIjoxNjIwMjIwNzc5LCJpZCI6MSwibmFtZSI6Im51aSJ9.K9Lk8Dw1r8lA1Ph136eEWh7F87L4nSkum0kAn959ScbCr8PbEePYkj_mvQ08KFunvwk7u2a-COrv2UwuYLHL4w

### GET private using sam's token
GET http://rpi4:3000/private HTTP/1.1
Content-Type: application/json; charset=UTF-8
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6ZmFsc2UsImV4cCI6MTYyMDIxOTQ3OCwiaWQiOjIsIm5hbWUiOiJzYW0ifQ.DesboHR9VmIvnErvXhP1gtNGGbjIsfyq-m4LNa8gDTCDul_fNPBDqTbHbVaz3L_kZLExJOFEN0OGLaLFbJRmXA
### GET admin while admin is true in token
GET http://rpi4:3000/admin HTTP/1.1
Content-Type: application/json; charset=UTF-8
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6dHJ1ZSwiZXhwIjoxNjIwMjIzMTU0LCJpZCI6MSwibmFtZSI6Im51aSJ9.TE7ks3hqdiKJ4AaI7QzQULwP5EKy-XWxVUkTbU_HKaYUyvHdVEubv61fEMzZZCYrcpp2hl1mQMvaJeNv56CUCw

### GET admin while admin is false in token
GET http://rpi4:3000/admin HTTP/1.1
Content-Type: application/json; charset=UTF-8
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6ZmFsc2UsImV4cCI6MTYyMDIyMDgzMSwiaWQiOjIsIm5hbWUiOiJzYW0ifQ.UUN2X9hswe0Xq22pYaz2kxF3BmcfxhmLcmVVjcTE-LBbmI_6Z9TXxMdfbPGrLi4iMbQh4cIzV-eoQ2t9YmfPJg

### Renew access token
POST http://rpi4:3000/token HTTP/1.1
Content-Type: application/json; charset=UTF-8
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6dHJ1ZSwiZXhwIjoxNjIwMjIzMTU0LCJpZCI6MSwibmFtZSI6Im51aSJ9.TE7ks3hqdiKJ4AaI7QzQULwP5EKy-XWxVUkTbU_HKaYUyvHdVEubv61fEMzZZCYrcpp2hl1mQMvaJeNv56CUCw

{ "refresh_token": "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjAzMDgyNDksInN1YiI6MX0.No74I75Mm8yrb5sTyRFXQP7bN27mUB6WR4AArWz-b2yRQUUJn39YcOv1y-fNDk6MjnMwF14CUl5k2iujfMQDxQ"}

###
nui
  "access_token": "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6dHJ1ZSwiZXhwIjoxNjIwMjIyNzQ5LCJpZCI6MSwibmFtZSI6Im51aSJ9.ZU-z-gBRSPbNZD0Ef6bavlsfyZfFeZa3_MQQjPDuNU886N70kcXTL6tW-iTZi_Ka4KQYGvFeIJr41dMNUiStmg",
  "refresh_token": "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjAzMDgyNDksInN1YiI6MX0.No74I75Mm8yrb5sTyRFXQP7bN27mUB6WR4AArWz-b2yRQUUJn39YcOv1y-fNDk6MjnMwF14CUl5k2iujfMQDxQ"

sam  "access_token": "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6ZmFsc2UsImV4cCI6MTYyMDIyMjc4MCwiaWQiOjIsIm5hbWUiOiJzYW0ifQ.f4giFobLNkdVOI-NeYp4t_CmleNzesJJLO65KCgaqKiDpBnneWcp_NznTRTVVeLcoWBvAzFua5WDSwnyUa6X-g",
  "refresh_token": "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjAzMDgyODAsInN1YiI6Mn0.hwd0dDVvbsJ3vF6N9aNNg2XWyliy3OCRob7Bvoi1JsgwJhLIdK1fjWpL1JWE104a0OFEfMt0kFJzCpCZ0sWjDA"