apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello
  name: hello-go
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - image: gcr.io/nattapon/hello-go
          name: hello-go
          ports:
            - containerPort: 8888
          securityContext:
            runAsUser: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
          resources:
            requests:
              memory: "10Mi"
              cpu: "50m"
            limits:
              memory: "20Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /live
              port: 8888
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 8888
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello
  name: hello-go
spec:
  type: LoadBalancer
  ports:
    - nodePort: 31002
      port: 8889
      protocol: TCP
      targetPort: 8888
  selector:
    app: hello
