GET http://localhost:8002/users/somboon HTTP/1.1

###
POST http://localhost:8002/users HTTP/1.1
Content-Type: application/json; charset=UTF-8

{"name":"Somboon"}

###
GET http://localhost:3000/users/nui HTTP/1.1

###
POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json; charset=UTF-8

{"name":"Somboon"}

###